spring.application.name=backend-service
spring.datasource.url=jdbc:postgresql://localhost:5432/discord_clone
spring.datasource.username=discord_admin
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true